export const BRIDGE_FRAME_TYPES = Object.freeze({
  REQUEST: "bridge.req",
  RESPONSE: "bridge.res",
  EVENT: "bridge.evt",
});

export const BRIDGE_ERROR_CODES = Object.freeze({
  UNKNOWN_NAMESPACE: "UNKNOWN_NAMESPACE",
  UNKNOWN_METHOD: "UNKNOWN_METHOD",
  INVALID_PARAMS: "INVALID_PARAMS",
  HANDLER_ERROR: "HANDLER_ERROR",
  NOT_AUTHENTICATED: "NOT_AUTHENTICATED",
  NOT_READY: "NOT_READY",
  INTERNAL: "INTERNAL",
});
